### ISSUE TITLE
Jonatan

### ISSUE THREAD

**Issue by CasperEngl** [linuxtheblack/CastMe#16]
* Tilføj knap til "My profile" på profil indstillinger
* Fix locale
* Fix sentence helper
* Put post titles under post cards
- [x] Tilføj knap til "My profile" på profil indstillinger og fjern den fra sidebar
- [ ] Fix locale
- [x] Fix sentence helper
- [x] Put post titles under post cards
- [x] Auth id is in_array on new conversation
- [ ] Post author is still active otherwise redirect
- [x] Add call us popup bottom right

**Comment by Jonatantwn** [comment]
Conversation not found - siger den hvis man klikker på post opslag på forsiden :p

**Comment by CasperEngl** [comment]
Tjek at auth id er in_array på new conversation

**Comment by CasperEngl** [comment]
Tjek at en post stadig har en aktiv scout, ellers redirect

**Comment by Jonatantwn** [comment]
Jobs på forside, listevisning oppfra-nedaf.

**Comment by Jonatantwn** [comment]
Ring til mig - popup dims
